export enum TimeOffType {
  VACATION = 'VACATION',
  SICK = 'SICK',
  PERSONAL = 'PERSONAL',
}

export enum RequestStatus {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  CANCELLED = 'CANCELLED',
}

export enum SyncSource {
  HCM_REALTIME = 'HCM_REALTIME',
  HCM_BATCH = 'HCM_BATCH',
  LOCAL_CACHE = 'LOCAL_CACHE',
}

export enum SyncTrigger {
  REALTIME_API = 'REALTIME_API',
  BATCH = 'BATCH',
  APPROVAL_CHECK = 'APPROVAL_CHECK',
  MANUAL = 'MANUAL',
}

export enum ScenarioType {
  TIMEOUT = 'TIMEOUT',
  INVALID_DIMENSION = 'INVALID_DIMENSION',
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  INSUFFICIENT_BALANCE = 'INSUFFICIENT_BALANCE',
}
